CREATE TABLE `CSC_MBHK_MEMBER`.`CUSTOMER_LOY_PROMO` (
                                                        `PK` bigint NOT NULL AUTO_INCREMENT,
                                                        `LOY_PROMO_ID` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                                                        `ACTIVE_FLG` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                                                        `ADMIN_FLG` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                                                        `ALWAYS_APPLY_FLG` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                                                        `BASE_PROMO_FLG` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                                                        `BU_ID` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                                                        `EXPORT_FLG` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                                                        `LOY_PROG_ID` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                                                        `NAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                                                        `OPT_IN_FLG` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                                                        `ORDER_FLG` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                                                        `PKG_ACRL_FLG` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                                                        `PROMO_NUM` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                                                        `END_DT` date DEFAULT NULL,
                                                        `FINAL_EXEC_DT` date DEFAULT NULL,
                                                        `NUM_TIMES` decimal(10,0) DEFAULT NULL,
                                                        `OPTIN_END_DT` date DEFAULT NULL,
                                                        `OPTIN_START_DT` date DEFAULT NULL,
                                                        `PTNR_PROC_DT` date DEFAULT NULL,
                                                        `START_DT` date DEFAULT NULL,
                                                        `DESC_TEXT` varchar(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                                                        `MKTG_OFFR_ID` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                                                        `PARTNER_ID` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                                                        `POINT_LIMIT_CD` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                                                        `PROD_INCLUSION_CD` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                                                        `PR_PROMO_LOGO_ID` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                                                        `PTNR_RVW_STAT_CD` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                                                        `PTNR_USER_ID` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                                                        `SRC_ID` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                                                        `SRM_REQ_ID` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                                                        `SUB_TYPE_CD` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                                                        `TIER_ID` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                                                        `TYPE_CD` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                                                        `LOY_CHANNEL` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                                                        `PROMO_ID` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                                                        `AVL_TO_PROCFLW_FLG` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                                                        `EFF_VCHR_PRD_TP_CD` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                                                        `EFF_VCHR_PRD_VAL` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                                                        `RULE_MODEL_CD` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                                                        `SM_DESC_TEXT` varchar(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                                                        `CREATED` datetime DEFAULT NULL,
                                                        `CREATED_BY` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                                                        `LAST_UPDATED` datetime DEFAULT NULL,
                                                        `LAST_UPDATED_BY` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                                                        `DB_LAST_UPDATED` datetime DEFAULT NULL,
                                                        PRIMARY KEY (`PK`) USING BTREE,
                                                        KEY `LOY_PROMO_ID` (`LOY_PROMO_ID`) USING BTREE,
                                                        KEY `IDX_LAST_UPDATED` (`LAST_UPDATED`) USING BTREE
) ENGINE=InnoDB;

CREATE TABLE `CSC_MBHK_MEMBER`.`CUSTOMER_LOY_TXN_ESSO` (
                                                           `PK` bigint NOT NULL AUTO_INCREMENT,
                                                           `LOY_TXN_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                                           `TXN_DT` datetime DEFAULT NULL,
                                                           `CREATED` datetime NOT NULL,
                                                           `LAST_UPDATED` datetime DEFAULT NULL,
                                                           `TYPE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                                                           `UPD_FLAG` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT 'N',
                                                           PRIMARY KEY (`PK`) USING BTREE,
                                                           KEY `LOY_TXN_ID` (`LOY_TXN_ID`),
                                                           KEY `TXN_DT` (`TXN_DT`),
                                                           KEY `TYPE` (`TYPE`)
) ENGINE=InnoDB;